run:
  skip-dirs:
    - tool
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo

linters:
  enable:
    - gocyclo
    - revive
  disable:
    - exhaustive
    - asciicheck
    - scopelint
  presets:
    - bugs
    - unused
    - format

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    ignore: fmt:.*,io/ioutil:^Read,^Close|^Write|^Shutdown
